version: 2.1
jobs:
  build:
    docker:
      - image: alpine:3.7
        auth:
          username: mydockerhub-user
          password: $DOCKERHUB_PASSWORD  # context / project UI env-var reference
    steps:
      - checkout
      - run:
          name: Test the DB
          command: |
            npm run test
      - run:
          name: Code Has Arrived
          command: |
            echo '^^^Testinf concluded^^^'
