version: 2.1
orbs:
  node: circleci/node@3.0.0
jobs:
  test:
    docker:
      - image: cimg/node:12.18.3
        auth:
          username: mydockerhub-user
          password: $DOCKERHUB_PASSWORD  # context / project UI env-var reference
    steps:
      - checkout
      - node/install-packages # Utilize commands in steps
      - node/test

